resources:
  requests:
    cpu: 200m
    memory: 100Mi
  limits:
    cpu: 300m
    memory: 200Mi
metrics:
  enabled: false
rules:
  enabled: false
image: rg.fr-par.scw.cloud/locust-qa-public/locust-operator
