{{- if .Values.rules.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Chart.Name }}-rules
spec:
{{ .Files.Get "alerts/alerts_rules.yaml" | indent 2 }}
{{ end }}
