{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
{{- end -}}
